######################################################################################
###  ██╗░░░░░██╗░██████╗░██╗░░██╗████████╗░██╗░░░░░░░██╗░█████╗░██╗░░░░░███████╗   ###
###  ██║░░░░░██║██╔════╝░██║░░██║╚══██╔══╝░██║░░██╗░░██║██╔══██╗██║░░░░░██╔════╝   ###
###  ██║░░░░░██║██║░░██╗░███████║░░░██║░░░░╚██╗████╗██╔╝██║░░██║██║░░░░░█████╗░░   ###
###  ██║░░░░░██║██║░░╚██╗██╔══██║░░░██║░░░░░████╔═████║░██║░░██║██║░░░░░██╔══╝░░   ###
###  ███████╗██║╚██████╔╝██║░░██║░░░██║░░░░░╚██╔╝░╚██╔╝░╚█████╔╝███████╗██║░░░░░   ###
###  ╚══════╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░░░░╚═╝░░░╚═╝░░░╚════╝░╚══════╝╚═╝░░░░░   ###
######################################################################################
# Связь с разработчиком:
# VK - @lightwolf7
# TG - @lightwolf
messages:
  no-permissions: "&cУ вас недостаточно прав для использования данной команды."
  config-reloaded: "&aКонфиг перезагружен."
  reload-usage: "&aИспользуйте: &e/lwregions reload"
  not-enough-args: "&cНедостаточно аргументов."

settings:
  update_time: 1.5 # Частота обновления в секундах

# Форматы (%region - название региона)
global: "&8▪ &e&lНЕТ РЕГИОНА &8▪"
format: "&c❌ &c&lТЕРРИТОРИЯ ЗАНЯТА &c❌"
owner: "&e▪ &a&lВАШ РЕГИОН &e▪"
spawn: "&e▪ &c&lСПАВН &e▪"


# Кастомные регионы
custom-regions:
  shop: "&e▪ &c&lМАГАЗИН &e▪"
  pvp: "&e▪ &c&lПВП &e▪"
  event: "&8▪ &e&lИВЕНТ &8▪"